spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  pattern:
#    console: "%d - %msg%n"
#  path: D:/log
  file: D:/log/sell.log
level: debug

server:
  context-path: /sell
